"""
ORC Onboarding Flow
Handles first-time setup and configuration
"""

import os
from pathlib import Path
from typing import Optional, Dict
from rich.console import Console
from rich.prompt import Prompt, Confirm
from rich.panel import Panel
from rich.table import Table


class ORCOnboarding:
    """Handles first-time ORC setup"""
    
    def __init__(self):
        self.console = Console()
        self.config_dir = Path.home() / ".orc"
        self.env_file = self.config_dir / ".env"
        
    def needs_onboarding(self) -> bool:
        """Check if onboarding is needed"""
        # Check if .env file exists with API key
        if not self.env_file.exists():
            return True
        
        # Check if any API key is configured
        if self.env_file.exists():
            content = self.env_file.read_text()
            if "API_KEY" in content and len(content.strip()) > 10:
                return False
        
        return True
    
    def run(self) -> Dict[str, str]:
        """
        Run the onboarding flow.
        
        Returns:
            Dict with configuration
        """
        self.console.clear()
        
        # Welcome message
        self.console.print()
        self.console.print(Panel.fit(
            "[bold cyan]Welcome to ORC![/bold cyan]\n\n"
            "Let's get you set up with AI integration.\n"
            "This will only take a minute.",
            border_style="cyan"
        ))
        self.console.print()
        
        # Step 1: Choose provider
        provider = self._choose_provider()
        
        # Step 2: Get API key
        api_key = self._get_api_key(provider)
        
        # Step 3: Save configuration
        self._save_config(provider, api_key)
        
        # Success message
        self.console.print()
        self.console.print(Panel.fit(
            "[bold green]Configuration Complete![/bold green]\n\n"
            f"AI Provider: {provider}\n"
            "API Key: Saved securely\n\n"
            "[dim]You can now use ORC's AI features![/dim]",
            border_style="green"
        ))
        self.console.print()
        
        return {"provider": provider, "api_key": api_key}
    
    def _choose_provider(self) -> str:
        """Let user choose AI provider"""
        self.console.print("[bold]Step 1:[/bold] Choose Your AI Provider\n")
        
        # Show provider options
        table = Table(show_header=True, header_style="bold cyan")
        table.add_column("Provider", style="cyan")
        table.add_column("Cost", style="yellow")
        table.add_column("Speed", style="green")
        table.add_column("Notes")
        
        table.add_row("groq", "FREE ⭐", "⚡ Very Fast", "Recommended for testing")
        table.add_row("openai", "$$", "Fast", "GPT-4, GPT-3.5")
        table.add_row("anthropic", "$$", "Medium", "Claude 3 (Opus, Sonnet)")
        table.add_row("deepseek", "$", "Fast", "Cost-effective")
        table.add_row("ollama", "FREE", "Medium", "Local models (no key needed)")
        
        self.console.print(table)
        self.console.print()
        
        # Get choice
        provider = Prompt.ask(
            "[cyan]Choose provider[/cyan]",
            choices=["groq", "openai", "anthropic", "deepseek", "ollama"],
            default="groq"
        )
        
        self.console.print()
        return provider
    
    def _get_api_key(self, provider: str) -> Optional[str]:
        """Get API key from user"""
        if provider == "ollama":
            self.console.print("[dim]Ollama runs locally - no API key needed[/dim]\n")
            return None
        
        self.console.print(f"[bold]Step 2:[/bold] Enter Your {provider.title()} API Key\n")
        
        # Show help for getting API key
        help_urls = {
            "groq": "https://console.groq.com/keys",
            "openai": "https://platform.openai.com/api-keys",
            "anthropic": "https://console.anthropic.com/keys",
            "deepseek": "https://platform.deepseek.com/api_keys"
        }
        
        if provider in help_urls:
            self.console.print(f"[dim]Get your API key at: {help_urls[provider]}[/dim]")
        
        self.console.print()
        
        # Get API key (hidden input)
        api_key = Prompt.ask(
            f"[cyan]Enter your {provider.upper()} API key[/cyan]",
            password=True
        )
        
        self.console.print()
        return api_key
    
    def _save_config(self, provider: str, api_key: Optional[str]) -> None:
        """Save configuration securely"""
        # Ensure config directory exists
        self.config_dir.mkdir(parents=True, exist_ok=True)
        
        # Save to .env file (secure storage)
        env_content = f"# ORC AI Configuration\n"
        env_content += f"# Generated by ORC Onboarding\n\n"
        env_content += f"ORC_AI_PROVIDER={provider}\n"
        
        if api_key:
            # Store API key with provider-specific name
            key_name = f"{provider.upper()}_API_KEY"
            env_content += f"{key_name}={api_key}\n"
        
        self.env_file.write_text(env_content)
        
        # Set restrictive permissions (owner only)
        if os.name != 'nt':  # Unix-like systems
            os.chmod(self.env_file, 0o600)
        
    def show_token_usage(self, input_tokens: int, output_tokens: int, provider: str) -> None:
        """
        Show token usage information.
        
        Args:
            input_tokens: Number of input tokens used
            output_tokens: Number of output tokens used
            provider: AI provider name
        """
        total = input_tokens + output_tokens
        
        # Cost estimation
        costs = {
            "groq": {"input": 0, "output": 0},
            "openai": {"input": 0.03, "output": 0.06},  # GPT-4 per 1K tokens
            "anthropic": {"input": 0.015, "output": 0.075},  # Claude Opus per 1K
            "deepseek": {"input": 0.00014, "output": 0.00028},
        }
        
        cost = 0
        if provider in costs:
            cost = (input_tokens / 1000 * costs[provider]["input"]) + \
                   (output_tokens / 1000 * costs[provider]["output"])
        
        # Create usage panel
        usage_text = f"[cyan]Tokens:[/cyan] {total:,}\n"
        usage_text += f"[dim]Input: {input_tokens:,} | Output: {output_tokens:,}[/dim]\n"
        
        if cost > 0:
            usage_text += f"[yellow]Cost:[/yellow] ${cost:.4f}"
        else:
            usage_text += f"[green]Cost:[/green] FREE"
        
        self.console.print()
        self.console.print(Panel(usage_text, title="Usage", border_style="dim"))


def run_onboarding_if_needed() -> bool:
    """
    Check if onboarding is needed and run it.
    
    Returns:
        True if onboarding was run, False otherwise
    """
    onboarding = ORCOnboarding()
    
    if onboarding.needs_onboarding():
        onboarding.run()
        return True
    
    return False
